# (C) Copyright 2015 Freescale Semiconductor, Inc.
# (C) Copyright 2016 Variscite Ltd.
# (C) Copyright 2020 Revolution Robotics, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := mx7d_roadrunner.o
